<img src="Fireblaze__2___3_-removebg-preview.png" width=300 height=250 />

## Table of Content

1. **[Array Creation](#Array)**
2. **[Access elements from Array ](#Access_elements_from_Array)**
3. **[Numpy random module](#Numpy_random_module)**
4. **[Arithmatic Operation](#Arithmatic_Operation)**
5. **[NumPy Functions](#NumPy_Functions)**
6. **[Concatenate](#Concatenate)**
7. **[Stacking & Splitting](#Stacking_&_Splitting)**

### Let's begin with some hands-on practice exercises

<a id="Array"> </a>
## <span style='color:Brown'> **1.Array Creation** </span>

### <span style='color:Blue'> **Question - 1.Create 1 D Array.** </span>

In [14]:
#write observation and code here
import numpy as np
a = [1, 2, 3, 4, 5, 6]
arr1 = np.array(a)
arr1

array([1, 2, 3, 4, 5, 6])

### <span style='color:Blue'> **Question - 1.1.Create 2 D Array.** </span>

In [10]:
#write observation and code here
b =[[1,2,3],[4,5,6],[7,8,9]]
arr2 =np.array(b)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### <span style='color:Blue'> **Question - 1.2.Create an array & check the diamension of array.** </span>

In [17]:
#write observation and code here
b = np.array([1, 2, 3, 4, 5])
print(b.ndim)



1


### <span style='color:Blue'> **Question - 1.3.Create an array with boolean values.** </span>

In [2]:
#write observation and code here

import numpy as np

boolean_array = np.array([True, False, True, False])
boolean_array

array([ True, False,  True, False])

<a id="Access_elements_from_Array"> </a>
## <span style='color:Brown'> **2.Access elements from Array** </span>

### <span style='color:Blue'> **Question - 2.Create an array & perform below operation.** </span>
**Given array:[ 30, 60, 90, 80, 190]**

In [18]:
#write observation and code here
arr1 =([ 30, 60, 90, 80, 190])
print(arr1)

[30, 60, 90, 80, 190]


### <span style='color:Blue'> **Question - 2.1.Access the 3rd element from an array.** </span>
**Required o/p :** 90

In [19]:
#write observation and code here
arr1[2]

90

### <span style='color:Blue'>**Question - 2.2.Write a code to retrive the elements.** </span>
**Required o/p :** array([30, 90, 190])

In [25]:
#write observation and code here
arr1[::2]

[30, 90, 190]

### <span style='color:Blue'> **Question - 2.3.reverse the above given array .** </span>

In [27]:
#write observation and code here
arr1[::-1]

[190, 80, 90, 60, 30]

<a id="Numpy_random_module"></a>
## <span style='color:Brown'> **3. Numpy random module** </span>

### <span style='color:Blue'> **Question - 3.Create 1D Array with integer values.** </span>
**Note:** Use random module function

In [28]:
#write observation and code here
integer_array = [1, 2, 3, 4, 5]

for element in integer_array:
    print(element)

1
2
3
4
5


<a id="Arithmatic_Operation"></a>
## <span style='color:Brown'> **4. Arithmatic Operations** </span>

### <span style='color:Blue'> **Question - 4.Create two numpy 1D array.** </span>

In [29]:
#write observation and code here
import numpy as np


array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([10, 20, 30, 40, 50])

# Print the two arrays
print( array1)
print( array2)

[1 2 3 4 5]
[10 20 30 40 50]


### <span style='color:Blue'> **Question - 4.1 Add above array.** </span>

In [31]:
#write observation and code here
array1+array2

array([11, 22, 33, 44, 55])

### <span style='color:Blue'> **Question - 4.2.Substract above array.** </span>

In [32]:
#write observation and code here
array1-array2

array([ -9, -18, -27, -36, -45])

### <span style='color:Blue'> **Question - 4.3.Perform division operation on array.** </span>

In [35]:
#write observation and code here
array1/array2

array([0.1, 0.1, 0.1, 0.1, 0.1])

### <span style='color:Blue'> **Question - 4.4.Perform Multiplication operation on above two array .** </span>

In [36]:
#write observation and code here
array1*array2

array([ 10,  40,  90, 160, 250])

<a id="NumPy_Functions"></a>
## <span style='color:Brown'> **5.Numpy_Functions** </span>

### <span style='color:Blue'> **Question - 5.Create new numpy array & perform below operation .** </span>

In [38]:
#write observation and code here
import numpy as np
new_array = np.array([1, 2, 3, 4, 5])
print( new_array)


[1 2 3 4 5]


**Calulate the standard deviation of above array**

In [39]:
#write observation and code here
std_deviation = np.std(new_array)
std_deviation 

1.4142135623730951

**Calculate the varience**

In [40]:
#write observation and code here
variance = np.var(new_array)
variance

2.0

**Calculate the square of each elements of an array**

In [41]:
#write observation and code here
squared_array = np.square(new_array)
squared_array

array([ 1,  4,  9, 16, 25])

**Find out the maximum value from the array**

In [43]:
#write observation and code here
max_val = np.max(new_array)
max_val

5

**Find out the minimum value from the array**

In [42]:
#write observation and code here
min_value = np.min(new_array)
min_value 

1

<a id="Concatenate"></a>
## <span style='color:Brown'> **6. Concatenate** </span>

### <span style='color:Blue'> **Question - 6.Create two new numpy array & concatenate them column wise .** </span>

In [44]:
#write observation and code here
import numpy as np

# Create two new NumPy arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Concatenate the arrays column-wise
concatenated_array = np.concatenate((array1.reshape(-1, 1), array2.reshape(-1, 1)), axis=1)

print(array1)
print(array2)
print("\nConcatenated Array (column-wise):")
print(concatenated_array)


[1 2 3]
[4 5 6]

Concatenated Array (column-wise):
[[1 4]
 [2 5]
 [3 6]]


### <span style='color:Blue'> **Question - 7.Create two numpy array & concatenate them row wise .** </span>

In [47]:
#write observation and code here
import numpy as np

# Create two new NumPy arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

concatenated_array = np.concatenate((array1.reshape(1, -1), array2.reshape(1, -1))),# axis=0)

print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)
print("\nConcatenated Array (row-wise):")
print(concatenated_array)


Array 1:
[1 2 3]

Array 2:
[4 5 6]

Concatenated Array (row-wise):
(array([[1, 2, 3],
       [4, 5, 6]]),)


<a id="Stacking_&_Splitting"></a>
## <span style='color:Brown'> **7. Staking & Splitting** </span>

### <span style='color:Blue'> **Question - 8.Create two new numpy array stack them horizentally .** </span>

In [48]:
#write observation and code here
import numpy as np

# Create two new NumPy arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Stack the arrays horizontally
stacked_array = np.hstack((array1.reshape(-1, 1), array2.reshape(-1, 1)))

# Print the stacked array
print(array1)
print(array2)
print("\nStacked Array (horizontally):")
print(stacked_array)


[1 2 3]
[4 5 6]

Stacked Array (horizontally):
[[1 4]
 [2 5]
 [3 6]]


### <span style='color:Blue'> **Question - 9.Create two new numpy array stack them verically .** </span>

In [49]:
#write observation and code here
import numpy as np

# Create two new NumPy arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Stack the arrays vertically
stacked_array = np.vstack((array1, array2))



print(array1)
print(array2)
print("\nStacked Array (vertically):")
print(stacked_array)


[1 2 3]
[4 5 6]

Stacked Array (vertically):
[[1 2 3]
 [4 5 6]]


### <span style='color:Blue'> **Question - 10.What is the difference between Stack & concatenate, give one example.** </span>

In [52]:

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Concatenate horizontally
concatenated_array = np.concatenate((array1.reshape(-1, 1), array2.reshape(-1, 1)), axis=1)


In [53]:

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Stack arrays (creates a 2D array)
stacked_array = np.stack((array1, array2), axis=0)


## The End2