### Arithmetic Expression3

In [2]:
import numpy as np

In [3]:
arr1= np.arange(1,7).reshape(2,3)

In [4]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
arr1.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [6]:
arr2 = arr1.T
arr2

array([[1, 4],
       [2, 5],
       [3, 6]])

In [7]:
arr1@arr2 #dot product

array([[14, 32],
       [32, 77]])

In [8]:
np.dot(arr1,arr2)

array([[14, 32],
       [32, 77]])

In [9]:
arr3 = np.arange(1,10).reshape(3,3)
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Square root of the array!`3

In [10]:
np.sqrt(arr3)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [11]:
np.sqrt(arr2)

array([[1.        , 2.        ],
       [1.41421356, 2.23606798],
       [1.73205081, 2.44948974]])

In [12]:
#exp Function
np.exp(arr3)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [13]:
arr4 = np.array([11,33,55,77,99])
arr5 = np.array([22,44,66,88])

In [14]:
arr4

array([11, 33, 55, 77, 99])

In [15]:
arr5

array([22, 44, 66, 88])

In [16]:
arr4.max()

99

In [17]:
arr4.min()

11

In [18]:
arr5.min()

22

In [19]:
arr5.max()

88

In [24]:
mse1 = np.array([11,2,16,11,5,30])
mse2 = np.array([15,7,8,10,1,21])

In [26]:
mse1.max()

30

In [27]:
mse2.max()

21

In [28]:
np.maximum(mse1,mse2)

array([15,  7, 16, 11,  5, 30])

In [29]:
np.minimum(mse1,mse2)

array([11,  2,  8, 10,  1, 21])

In [30]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
arr3.mean()

5.0

In [33]:
arr3.sum()

45

In [34]:
arr3.sum(0)# 0 is for vertical operation of Function in numpy.

array([12, 15, 18])

In [35]:
arr3.mean(0)

array([4., 5., 6.])

In [36]:
arr3.sum(1)# 1 is for horizental operation of Function in numpy.

array([ 6, 15, 24])

In [38]:
arr3.mean(1)

array([2., 5., 8.])

In [39]:
np.add(arr1,arr1)

array([[ 2,  4,  6],
       [ 8, 10, 12]])

### Random Module3

In [40]:
import numpy as np

In [41]:
np.random.randint(1,101,size =10)

array([ 8, 93, 48, 81, 16, 24, 99, 20, 82, 98])

In [42]:
np.random.randint(1,101,10)

array([83, 85, 28, 88, 63, 58,  7, 27, 67, 99])

In [43]:
from numpy.random import randint

In [44]:
randint(1,51,10)

array([ 1, 36,  6, 45, 26, 41, 22, 30, 45, 24])

In [45]:
from numpy. random import randn

In [49]:
randn(10)

array([-0.4619436 , -0.70813294, -0.6209872 , -0.37923714,  0.50113548,
       -0.17051553,  0.69769916,  0.35660211,  0.05582753,  0.005475  ])

In [50]:
randn(2,3)

array([[ 0.60807261, -0.09482885, -0.77713942],
       [ 1.2027305 , -1.30562948,  0.37769886]])

### Where 3

In [51]:
import numpy as np

In [68]:
A = np.array([1,2,3])
B = np.array([10,20,30])
C = np.array([True,False,True])


In [69]:
print(A)
print(B)
print(C)

[1 2 3]
[10 20 30]
[ True False  True]


In [70]:
#np.Where(Condition , if True, If False)
np.where(C,A,B)

array([ 1, 20,  3])

In [71]:
A = np.array([1,2,3])
B = np.array([10,20,30])
C = np.array([False,False,False])


In [72]:
np.where(C,A,B)

array([10, 20, 30])

In [76]:
np.where(C,B,A)

array([10, 20, 30])

In [73]:
A = np.array([1,2,3])
B = np.array([10,20,30])
C = np.array([True,True,True])


In [75]:
np.where(C,B,A)

array([10, 20, 30])

In [77]:
np.where(C,A,B)

array([1, 2, 3])

In [78]:
arr1 = np.random.randint(1,11,10)

In [79]:
arr1

array([ 4,  3,  5,  2,  6,  2,  2, 10,  4,  6])

In [80]:
np.where(arr1<5)

(array([0, 1, 3, 5, 6, 8], dtype=int64),)

In [81]:
np.where(arr1>5)

(array([4, 7, 9], dtype=int64),)

In [82]:
np.where(arr1==5)

(array([2], dtype=int64),)