In [2]:
import numpy as np

li_arr =[i for i in range(0,100)]
np_arr =np.arange(100)

print(li_arr)
print(np_arr)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [3]:
# Size of one element in numpy arRAY
print(np_arr.itemsize)

##Size of 100 elements in numpy array
print(np_arr.itemsize * np_arr.size)

4
400


In [5]:
import sys

##size of one elemnet in list

a =10
print(sys.getsizeof(a))

##Size of 100 elements in list
print(sys.getsizeof(1)* len(li_arr))


28
2800


In [8]:
import numpy as np



In [9]:
a = [1,2,3]
b =np.array(a)
print(b)
print(type(b))



[1 2 3]
<class 'numpy.ndarray'>


In [10]:
a = [1,2,3,'5','s',4.5]
b =np.array(a, dtype =str)
print(b)

['1' '2' '3' '5' 's' '4.5']


In [13]:
a = [1,2,3,'5',4.5]
b =np.array(a, dtype =float)
print(b)

[1.  2.  3.  5.  4.5]


In [16]:
a = [1,2,3,'5',4.5]
b =np.array(a, dtype =int)
print(b)

[1 2 3 5 4]


In [17]:
import numpy as np

In [18]:
b = np.ones(3)

In [19]:
b

array([1., 1., 1.])

In [25]:
b = np.ones((2,3))
b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [24]:
b = np.zeros(3)

In [21]:
b

array([0., 0., 0.])

In [26]:
b = np.zeros((3,3))

In [27]:
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [32]:
b= np.full(3,5)

In [33]:
b

array([5, 5, 5])

In [37]:
b= np.full ((3,3),5)
b

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [39]:
b = np.empty(3)
b


array([0., 0., 0.])

In [40]:
 b = np.arange(10)

In [41]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
b = np.arange(2,10)

In [43]:
b

array([2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
b = np.arange(2,20,2)

In [45]:
b


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [49]:
b = np.linspace(2,10)
b

array([ 2.        ,  2.16326531,  2.32653061,  2.48979592,  2.65306122,
        2.81632653,  2.97959184,  3.14285714,  3.30612245,  3.46938776,
        3.63265306,  3.79591837,  3.95918367,  4.12244898,  4.28571429,
        4.44897959,  4.6122449 ,  4.7755102 ,  4.93877551,  5.10204082,
        5.26530612,  5.42857143,  5.59183673,  5.75510204,  5.91836735,
        6.08163265,  6.24489796,  6.40816327,  6.57142857,  6.73469388,
        6.89795918,  7.06122449,  7.2244898 ,  7.3877551 ,  7.55102041,
        7.71428571,  7.87755102,  8.04081633,  8.20408163,  8.36734694,
        8.53061224,  8.69387755,  8.85714286,  9.02040816,  9.18367347,
        9.34693878,  9.51020408,  9.67346939,  9.83673469, 10.        ])

In [50]:
print(b[1])

2.163265306122449


In [51]:
b = np.linspace(2,10,5)

In [52]:
b


array([ 2.,  4.,  6.,  8., 10.])

In [53]:
b = np.identity(3)

In [54]:
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [59]:
b = np.eye(3,4)

In [60]:
b


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [62]:
b = np.random.rand(3)
b

array([0.75257479, 0.11837151, 0.05085569])

In [66]:

b = np.random.randint(5,size=(3,4))
b

array([[2, 0, 4, 1],
       [4, 2, 0, 1],
       [0, 4, 4, 3]])

In [67]:
import numpy as np

In [68]:
li =[1,2,3,4]
arr =np.array(li)
print(li)
print(arr)

[1, 2, 3, 4]
[1 2 3 4]


In [69]:
print(arr.data)
print(arr.shape)
print(arr.dtype)
print(arr.strides)

(4,)
int32
(4,)


In [71]:
li_2d = [[1,2,3],[4,5,6],[7,8,9]]
arr_2d =np.array(li_2d)

print(li_2d)
print(arr_2d)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [72]:
print(arr_2d.data)
print(arr_2d.shape)
print(arr_2d.dtype)
print(arr_2d.strides)

(3, 3)
int32
(12, 4)


In [73]:
print(li[3])

4


In [74]:
print(li[1:4])

[2, 3, 4]


In [75]:
print([arr[1:4]])

[array([2, 3, 4])]


In [76]:
print(li_2d)
print(arr_2d)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [79]:
print(li_2d[2][1])
print(arr_2d[2][1])

8
8


In [82]:
print(li_2d[2][:2])
print(arr_2d[2][:3])

[7, 8]
[7 8 9]


### Mathematics  OPeration3

In [83]:
import numpy as np

In [84]:
li =[1,2,3,4,5,6]
a = np.random.randint(1,20,5)
b = np.random.randint(1,20,5)

In [85]:
print(li)
print(a)
print(b)

[1, 2, 3, 4, 5, 6]
[17  2 16 10  7]
[18  2 13  8  6]


In [86]:
li = [i+1 for i in li]
li

[2, 3, 4, 5, 6, 7]

In [88]:
a = a+1
a

array([19,  4, 18, 12,  9])

In [90]:
c = a+b
c

array([37,  6, 31, 20, 15])

In [91]:
d = a- b
d

array([1, 2, 5, 4, 3])

In [93]:
print(a.sum())
print(a.mean())
print(a.min())
print(a.argmin())
print(a.max())
print(a.argmax())

62
12.4
4
1
19
0


In [94]:
a

array([19,  4, 18, 12,  9])

In [95]:
b

array([18,  2, 13,  8,  6])

In [96]:
a>b

array([ True,  True,  True,  True,  True])

In [97]:
a<b

array([False, False, False, False, False])

In [98]:
a==b

array([False, False, False, False, False])

In [99]:
print(np.logical_or(a,b))

[ True  True  True  True  True]


In [100]:
print(np.logical_and(a,b))

[ True  True  True  True  True]


In [102]:
print(np.logical_not(b))

[ True  True  True  True  True]


## Boolen Indeinty2

### Boolen indexing3

In [10]:
import numpy as np
##boolen indexing

In [11]:
a = np.array(['t','b','r','d','e','f','z','a'])
b = np.random.randint(1,20,8)
print(a)
print(b)

['t' 'b' 'r' 'd' 'e' 'f' 'z' 'a']
[12  5  1  7 10 10 10 13]


In [12]:
print(b>10)

[ True False False False False False False  True]


In [14]:
bool_arr =b>10
print(bool_arr)
new_arr = b[bool_arr]
print(new_arr)

[ True False False False False False False  True]
[12 13]


In [15]:
new_arr = b[b<10]
new_arr

array([5, 1, 7])

In [16]:
new_arr = b[(b>10)& (b<18)]
new_arr

array([12, 13])

In [17]:
print(b)

[12  5  1  7 10 10 10 13]


In [18]:
import numpy as np

In [19]:
a = np.random.randint(1,30,(5,6))
print(a)

[[ 6 22  8 15  4  2]
 [10 20  1 25 19 27]
 [11 29 18 12 28  6]
 [21 12 14 23 14 16]
 [ 7 24 24 23 16 16]]


In [21]:
a>15

array([[False,  True, False, False, False, False],
       [False,  True, False,  True,  True,  True],
       [False,  True,  True, False,  True, False],
       [ True, False, False,  True, False,  True],
       [False,  True,  True,  True,  True,  True]])

In [ ]:
b

### brodcasting3

In [23]:
import numpy as np 

In [24]:
x = np.random.randint(1,10,(3,3))
y = np.random.randint(1,10,(3,3))
print(x)
print(y)

[[1 7 1]
 [1 1 2]
 [4 2 1]]
[[8 7 1]
 [3 2 9]
 [4 4 2]]


In [25]:
ans = x-y
print(ans)

[[-7  0  0]
 [-2 -1 -7]
 [ 0 -2 -1]]


In [26]:
x = np.random.randint(1,10,(3,3))
y = np.random.randint(1,10,(3))
print(x)
print(y)

[[9 2 8]
 [5 6 8]
 [8 1 4]]
[3 8 6]


In [27]:
ans = x-y
print(ans)

[[ 6 -6  2]
 [ 2 -2  2]
 [ 5 -7 -2]]
