In [3]:
import numpy as np

In [5]:
a  = np.array([1,2,3,4,5])
print(a)
print(type(a))

print(a.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [6]:
b =np.array([[1],[2],[3],[4],[5]])
print(b)
print(b.shape)

[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)


In [7]:
c = np.array([[1,2,3],[4,5,6]])
print(c)
print(c.shape)
print(c[1][1])

[[1 2 3]
 [4 5 6]]
(2, 3)
5


In [14]:
##Create Zerose ,ones,Custom Array
a = np.zeros((3,3))
print(a)

b = np.ones((2,3))
print(b)

##array of some contants
c = np.full((3,2),5)
print(c)

#indentity Matrix - Size /Square Matrix
d = np.eye(4)
print(d)

#random Matrix

randomMatrix = np.random.random((2,3))
print(randomMatrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5]
 [5 5]
 [5 5]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.15123764 0.23398044 0.09152047]
 [0.82461689 0.26204688 0.46964384]]


In [15]:
print(randomMatrix[:,2])

[0.09152047 0.46964384]


In [17]:
z = np.zeros((3,3))
print(z)
z[1,:]=5
z[:,-1]=7
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 7.]
 [5. 5. 7.]
 [0. 0. 7.]]


In [18]:
#Datavtype
print(z.dtype)

float64


In [22]:
##Mathmatical Operation

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

##Element wise Addition
print(x+y)
print(np.add(x,y))
print(x-y)
print(np.subtract(x,y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


In [25]:
print(x*y)
print(np.multiply(x,y))
print(x/y)
print(np.divide(x,y))

print(np.sqrt(x))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [27]:
##MAtrix Multi[laction / dot product
print(x)
print(y)

print(x.dot(y))
print(np.dot(x,y))


[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [28]:
##multipacation of vecotors

a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
print(a.dot(b))

30


In [29]:
print(a)

[1 2 3 4]


In [30]:
print(sum(a))

10


In [31]:
print(x)

[[1 2]
 [3 4]]


In [32]:
print(np.sum(x))
print(np.sum(x,axis =0))

10
[4 6]


In [33]:
print(np.sum(x))
print(np.sum(x,axis =1))

10
[3 7]


In [34]:
##satcking of array
print(a)
b = b**2
print(b)

[1 2 3 4]
[ 1  4  9 16]


In [50]:
np.stack((a,b),axis =0)



    

ValueError: all input arrays must have the same shape

In [49]:
#Reshape of array
a = a.reshape((4,2))
print(a)

[[ 1  1]
 [ 2  4]
 [ 3  9]
 [ 4 16]]


### Numpy Random Module

- rand : Random Value in agivine Shape
- randn : Returns a simple (or Shape) from the "Standard normal" distibution.
- randint :Return Random integers from low (inclusive) to high (exclusive).
- random : Retrun random floats in the half-open interval [0.0,1.0]  
- choise : Generator a random sample from a given 1-Darrray
- shuffle :Shuffles the contents of a sequence
    
    


In [51]:
a = np.arange(10)+5
print(a)

[ 5  6  7  8  9 10 11 12 13 14]


In [54]:
np.random.shuffle(a)
print(a)


[ 9 13 10 11  5 12  6  7 14  8]


In [61]:
#return values from a standard Normal Distrubuiton
a = np.random.randn(2,3)
print(a)

a = np.random.randint(5,10,3)
print(a)

##randmly pick one element from a array
element = np.random.choice([1,2,4,5,1,1])
print(element)

[[ 1.28026679 -0.37155257 -1.25490984]
 [ 0.88555251  1.45939234 -0.18461375]]
[9 6 9]
1


### Some more numpy Function -Statistics

- min,max
-mean
- median
- average
- variance
- standard devidation3

In [66]:
a = np.array([[1,2,3,4],[7,5,6,0]])
print(a)
print(np.min(a))

print(np.min(a,axis =0))
print(np.min(a,axis =1))

[[1 2 3 4]
 [7 5 6 0]]
0
[1 2 3 0]
[1 0]


In [69]:
b = np.array([1,2,3,4,5])
m =sum(b)/5
print(m)

print(np.mean(b))
print(np.mean(a,axis=0))
print(np.mean(a,axis=1))

3.0
3.0
[4.  3.5 4.5 2. ]
[2.5 4.5]
